services:
  auction_database:
    image: postgres:latest
    environment:
      POSTGRES_USER: auction_user
      POSTGRES_PASSWORD: auction_password
      POSTGRES_DB: auction_db
    ports:
      - "5432:5432"
    volumes:
      - auction_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: auction_password
    ports:
      - "5050:80"
    depends_on:
      - auction_database
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  auction_ms:
    build: .
    depends_on:
      - auction_database
    environment:
      DATABASE_URL: postgres://auction_user:auction_password@auction_database:5432/auction_db
      GRPC_ADDRESS: "0.0.0.0:50052"
      RUST_LOG: "info"
    ports:
      - "50052:50052"
    restart: unless-stopped
    networks:
      - default

volumes:
  auction_data:
  pgadmin_data:

networks:
  default:
    driver: bridge
