//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "auction")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: String,
    pub item_id: String,
    pub title: String,
    pub description: Option<String>,
    pub category: String,
    pub start_time: DateTime,
    pub end_time: DateTime,
    pub base_price: Decimal,
    pub min_bid_increment: Decimal,
    pub highest_bid: Option<Decimal>,
    pub status: String,
    pub currency: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bid::Entity")]
    Bid,
}

impl Related<super::bid::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bid.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
