//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bid")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub auction_id: Uuid,
    pub user_id: String,
    pub amount: Decimal,
    pub created_at: DateTime,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::auction::Entity",
        from = "Column::AuctionId",
        to = "super::auction::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Auction,
}

impl Related<super::auction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Auction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
